
spring:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:testdb
  jms:
      listener:
       concurrency: 1
       max-concurrency: 1
      template:
       delivery-mode: persistent
      cache:
       # cache the session to the broker to increase the performance
       session-cache-size: 100
       producers: true
       
   # pub-sub-domain: true # by default jsm queue(point-to-point) is activated so we need to activate publisher/subscriber moderl
  activemq:
    #in-memory: true
    #this configuration improve the perfofmace by creating a pool of conncetion to the broker and use them frequently rethar than creating new one each time
   # pool: #this is native configuration that require org.messaginghub dependency
   #   enabled: true
   #   max-connections: 1000
    packages:
      trust-all: true
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
#resilience4j:
#  circuitbreaker:
#    instances: 
#      MongoBackend:
#        registerHealthIndicator: true
#        sliding-window-type: count-based
#        sliding-window-size: 5
#        record-exceptions:
#          - feign.FeignException
#        permitted-number-of-calls-in-half-open-state: 2
#        failure-rate-threshold: 40
#  retry:
#    instances:
#       MongoBackend:
#          max-attempts: 10
#          wait-duration: 1s
#          retry-exceptions:
#            - feign.FeignException

api:
  url: https://data.mongodb-api.com/app/data-ktqpf/endpoint/data/beta/action/insertOne
  secret:
    key: KeoteIu0I0IvkvHaSrT4KGu91bXYZ5mDq8CHz5eAD89ko1PB0qgV8sqSVVdnnZCB
mongo:
  cluster: Cluster0
  database: test
  collection: Events
queue:
  event:
    signin_success: SIGN_IN_SUCCESS
    signin_faild: SIGN_IN_FAILD
    signup_success: SIGN_UP_SUCCESS
    signup_faild: SIGN_UP_FAILD
    file_create: FIEL_CREATED
    file_reviewed: FILE_REVIEWED
jwt:
  key:
    secret: SECTRET_KEY1991
  time:
    expired: 878844122
url:
  users:
    signup: /jms/app/user/signup
    signin: /jms/app/user/signin